#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_nozdratenko_sdpo_lib_COMPorts */

#ifndef _Included_ru_nozdratenko_sdpo_lib_COMPorts
#define _Included_ru_nozdratenko_sdpo_lib_COMPorts
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     ru_nozdratenko_sdpo_lib_COMPorts
	 * Method:    getComPort
	 * Signature: (Ljava/lang/String;)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_ru_nozdratenko_sdpo_lib_COMPorts_getComPort
	(JNIEnv*, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
