# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    tags:
    - '*'
  pull_request:
    branches:
    - main

jobs:
  build:
  
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.0'

    - name: Install Dependency & Build 
      run: |
        cd ./src/main/frontend 
        npm install
        npm run build

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle
      run: |
          chmod +x gradlew  
          ./gradlew build
          
    - name: Store Version
      uses: actions/upload-artifact@v3
      with:
        name: build-jar
        path: .gradle/libs/release.jar

          
  update-servers:
    name: "sdpo-manager-version"
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: build-jar
    - name: Upload artifacts
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST  }}
        username: ${{ secrets.DEPLOY_USER  }}
        key: ${{ secrets.DEPLOY_KEY  }}
        port: ${{ secrets.DEPLOY_PORT  }}
        source: .gradle/libs/release.jar
        target: ${{ secrets.DEPLOY_TARGET  }}
    - name: Update repository
      uses: appleboy/ssh-action@master
      env: 
        TARGET_PATH: ${{ secrets.DEPLOY_TARGET  }}
      with:
        host: ${{ secrets.DEPLOY_HOST  }}
        username: ${{ secrets.DEPLOY_USER  }}
        key: ${{ secrets.DEPLOY_KEY  }}
        port: ${{ secrets.DEPLOY_PORT  }}
        script: |
            "${TARGET_PATH}"/update.sh
          

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    #- name: Publish to GitHub Packages
    #  run: ./gradlew publish
    #  env:
    #    USERNAME: ${{ github.actor }}
    #    TOKEN: ${{ secrets.GITHUB_TOKEN }}
